---
- hosts: localhost
  connection: local
  tasks:
    - name: Install Python 3.9
      include_role:
        name: software/utilities/python3
      vars:
        python3_version: python3.9

    - name: Install shawl reqs
      pip:
        requirements: /opt/shawl4/requirements.txt
        virtualenv: /opt/shawl4/venv
        virtualenv_python: python3.9

    - name: Clone latest version of shawl
      git:
        repo: https://github.com/dvolk/shawl4
        dest: /opt/shawl4

    - name: Copy desktop entry
      copy:
        src: shawl.desktop
        dest: /etc/xdg/applications/shawl.desktop
