---
- hosts: localhost
  connection: local
  tasks:
    - name: Install python 3.6
      yum:
        name:
          - python3
          - python3-devel
          - python3-pip

    - name: Clone latest version of shawl
      git:
        repo: https://github.com/dvolk/shawl4
        dest: /opt/shawl4

    - name: Upgrade pip
      pip:
        executable: /usr/bin/pip3
        name: pip
        state: latest

    - name: Install shawl reqs
      pip:
        executable: /usr/bin/pip3
        name:
          - argh
          - flask
          - humanize
          - paramiko
          - scp
          - markdown2

    - name: Copy desktop entry
      copy:
        src: shawl.desktop
        dest: /etc/xdg/applications/shawl.desktop
